camera0: 'LA'
camera1: 'RA'
frame_width: 1920
frame_height: 1080
mono_calibration_frames: 14
stereo_calibration_frames: 6
view_resize: 1
checkerboard_box_size_scale : 5.5
checkerboard_rows: 4
checkerboard_columns: 6
cooldown: 100